### PR TITLE
Adding  some content to the 'README' file by @JetCode123

### PR DESCRIPTION
**Pull request by JetCode123**

### CODE REVIEW

**Comment by xiaolu1988** [comment]
Can you merge this pull request on your 'Pull request' page ? 💭

**Comment by JetCode123** [comment]
> Can you merge this pull request on your 'Pull request' page ? 💭



> Can you merge this pull request on your 'Pull request' page ? 💭

No, I'm not capable of doing that ! 😢

**Comment by JetCode123** [comment]
> 

No, I'm not capable of doing that ! 😭

**Comment by JetCode123** [comment]
No, I'm not capable of doing that ! 😭

**Comment by xiaolu1988** [comment]
All right, I'll check in and Commit Merge!

**Pull request merged**
