### PR TITLE
Adding some content to the  'README.md' file

### PR DESCRIPTION
**Pull request by xiaolu1988**

### CODE REVIEW

**Comment by xiaolu1988** [comment]
I think this is quite a good change ! I'm 👍 to 🚢 it !

**Comment by xiaolu1988** [comment]
Make it easier to people to understand what this project is about.

**Comment by JetCode123** [comment]
Could you provide a little bit more explanation about this project ? 🖌️

**Comment by JetCode123** [comment]
Approval 👍 !

**Pull request merged**
